### ISSUE TITLE
No panel/tray icons

### ISSUE THREAD

**Issue by Chirunos** [Nerimity/nerimity-desktop#1]
![image](https://github.com/user-attachments/assets/6806e89f-29cf-41c2-810c-b6b4d0b8e71e)
(Rectangle icon with exclamation point is Nerimity's entry)

KWin (X)
LXQt 1.4
openSUSE Leap 15.6

I *suspect* these *might* be the culprit (I have no experience building Electron software):
1. `nerimity-desktop.png` is a symlink to `usr/share/icons/hicolor/0x0/apps/nerimity-desktop.png`, which a part of my environment doesn't understand
2. The icon is in a directory named `0x0` while the icon's resolution actually is 256x256, which a part of my environment doesn't understand

**Comment by SupertigerDev** [comment]
I probably wont fix this, but if someone could try to fix this and create a PR, I would appreciate it
